### ISSUE TITLE
spectrumdraw~ : Drawing issue with audio signal 2

### ISSUE THREAD

**Issue by lossius** [HISSTools/HISSTools_Impulse_Response_Toolbox#1]
There seems to be a bug in spectrumdraw~ where signal 2 gets scaled according to the overall gain of signal 1 rather than 2. Here are steps to reproduce using the below patch:

1. Start audio- Observe how signal 3 and 4 are displayed but not 1 or 2. Expected result: 2 should be displayed as well.
2. Hit the "0.2" message box. Expected result: Signal 1 should show up as well. Signal 2 should already be present. Observed result: Signal 1 AND 2 shows up. Additionally signal 1 and 2 are drawn as having similar intensity, even though noise~ in signal 1 is multiplied by 0.2 while pink~ in signal 2 is multiplied by 4.
3. Hit the "0" message box. Expected result: Signal 1 should disappear. Signal 2 should stay. Observed result: Both signal 1 and 2 disappear.

I'm using a version of spectrumdraw~ from December 5 2013, and I ran the patch in Max 6.1.10 in 32-bit mode.

<pre><code>
----------begin_max5_patcher----------
1047.3oc4Xs0iahCF84jeEV7XU1HeCLru0+CqTenppxAbHzBlrbYxLsp4295
K.AlIggVMimUs4AB3qGe9N9yG36qW4sq7dQsG3uAeDrZ02WuZkoHcAq5ddkW
A+93bdsoYdwkEEBYi2FacMh6aLk+gCBIn9P4I4FPygrZPcVpjmCJaSOz.ZJA
6Df7x1DQkpZtruZT+.kmIEwksRyng6JbeU5N8yvsvtRjsEksM4hFCZ5Kceor
oN6aBcYH7Pi20taWtsvtRNVIpUnm2jUJ+bkHtwtz8CCUcB3CQa82XlM8Evm5
6EuI9PlLcbOh7G0CTDU+DgMpSYIFdob2W9KTj2HfJ4EFL489pLdt2kEVlrec
gzk8i0q0W1rv.iTbRMWOIt7ty.5Vuqxdn4YOaKad3nvtj8rgLuYoEJyPKHCG
RBzWwvavJreRVA+xwJwODmKNqBx3WIp455r.ZjlQnnnNI1ypyBnAaYJEFEaZ
cf+rLp+aGi9tyNkI88IFljgWJS1IMoLSGIX891aRjA+FKMeJ0fflA.PhvKPj
Q+MTj8TNIBYRdQo9KPtPdykKHHD5ZtoStvlWtfc.2bKSI+i1HhJCxcpJGbjf
A6qJK.sGSTIUjo.dM3jHe.LNyyAz5Y.4uXOGS5AN.Y3c5M3cjC7bLKuKj0sp
kt1tWyfcO.Wlnh.IU7SudD9MoNLCZnNLaVpC91YWqle5rZuj61KyrbQepe7b
6kCcvVYw2R3w2HMOblTRiOb2lyVe8ZqB1qcJ4iYxud10Vt6BfT3bAv.GHrKD
007TwSXkWHI8y5LjFZM3YUDKIuJ05kjfB0IGrG0qt+pLnKbXeSF7kxRn2BXi
tTkyyF+YXEjDXSt3iedqf32NFQVlUKbNqPhL1Pny+p9NHuS8QEzpZKzVKdly
OJJSDi+LSwk4kUzt2ExlvHJBinXSpCnZkFsQWwvRKsJKwzIaefaYTDhEnaNM
P8iM8NLAQXjgdqmdxjOy00iJ6qD+aEWl1ETruiFFC8gOBJ0MOL0AT7AtDOtf
coSfKDxBojM23NFcXzmzqvKoS0WH9SaFdXz00FFfYzKFaoQPTTvDJfNlBZNj
E+UovFKuPA2V246ir+Y9TJX8eSgCYBbrAUEJLwTeebDEMAM3wnYbJteVsKsu
46Ghordb0VcmXHXQFIxMPw7MPezGi0P.5xmp7qKaqh62r1k2Abg.RTyRlzbx
3n1nWJiZzgrjDgb79hjrZtxKsYwCu5VvkBG821aY3A4F7Dr.77HP+ZhmEAm.
2Et7WJdbT3htD7PbGdHKUNSbCdvKkebi9IbozC1IvYIpYryDOz+WgFzBQyuh
vwdJF+3w6DU0cCoAHJmZew5iHXi4wLo8Qi+DuJwcY8sGYlDOdk5b+F0g9sU1
CbuOLvasdh9w5+CvRQQoV
-----------end_max5_patcher-----------
</code></pre>

**Comment by AlexHarker** [comment]
Hi,

Sorry for the late reply on this. It would appear that you have set the spectrum draw~ object so that curve 2 and curve 1 are drawing from input 1 on the attributes. Therefore, I don't see a bug here.

Alex

**Comment by lossius** [comment]
You're right, I didn't realise that this could be controlled from the inspector as well. Thanks!
