### ISSUE TITLE
hirt.convolver @file attribute ignored on load

### ISSUE THREAD

**Issue by iammacb** [HISSTools/HISSTools_Impulse_Response_Toolbox#7]
Instances of hirt.convolver loaded with patch ignore the @file attribute, but instances created in an open patcher do not.

**Comment by AlexHarker** [comment]
@steadykammer - can you take a look at this when you have a moment?

**Comment by steadykammer** [comment]
ooh, strange. works with hirt.convolutionreverb~ but not hirt.convolver~

**Comment by AlexHarker** [comment]
You'll get the same aural result, but hirt.convolver~ is more efficient if you don't need any of the extra features of the reverb.

**Comment by steadykammer** [comment]
Actually I spoke to soon. Here the @file and @file* attributes across both devices are saving and recalling perfectly. This works for me:
/Users/stkr/Desktop/Screen Shot 2022-02-10 at 22.10.46.png
Are your files outside of the search path? If so remember the entire path, as a symbol, is required. The reference docs give tips on this.
Are you on macOS or Windows? Any other information, such as a copy compressed patch, would be very useful, thanks.

**Comment by AlexHarker** [comment]
Doesn't look like the pic attached there correctly.

**Comment by iammacb** [comment]
[ir_test.zip](https://github.com/HISSTools/HISSTools_Impulse_Response_Toolbox/files/8044366/ir_test.zip)
Here is a zip containing the patch and IRs. The IRs are in the same directory as the patch, so should be part of the search path. I am using Max 8 on macOS Big Sur 11.6.1

**Comment by iammacb** [comment]
On my end, hirt.convolutionreverb~ works as expected, but hirt.convolver~ doesn't.

**Comment by iammacb** [comment]
Thank you!

**Comment by steadykammer** [comment]
It is a very strange bug as the two main abstractions are using identical file loading abstractions, so this will take more time to look into as that particular code has not been touched for years.
The workaround:
Use hirt.convolutionreverb~ instead for now, and turn off every section you are not using - most parts are cpu-muted if they are off.
In the longer run, I will let you know when i have a fix.
<img width="518" alt="Screen Shot 2022-02-11 at 13 07 06" src="https://user-images.githubusercontent.com/34286499/153588986-662802b5-a4a7-4fec-8900-572e5ed1736c.png">

**Comment by steadykammer** [comment]
OK, this @file bug on hirt.convolver~ is fixed and pushed. It was a really nasty ordering issue :-)
Thanks for bringing it to our attention so clearly.
If you wait a few days we will have this all packaged up and released to the Max Package Manager. We just have a few more minor things to check and then we are good to go.

**Comment by AlexHarker** [comment]
(You are welcome to grab the package from this repo and test if you want to get it early)
